<html lang="en"><head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="img/icons/favicon.ico">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main_login.css">
<!--===============================================================================================-->
</head>

<!-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
<?php echo $this->flashSession->output(); 
 
 $username='';
 $password='';
 $rememberMe='';

 if($this->cookies->has("username") && $this->cookies->has("password") )
 {
     $username=$this->cookies->get("username");
     $password=$this->cookies->get("password");
     $rememberMe='checked';
 }
?>
<!-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->

<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt="" style="will-change: transform; transform: perspective(300px) rotateX(0deg) rotateY(0deg);">
					<img src="img/img-01.png" alt="IMG">
				</div>

				<form action="" method="post" class="login10-form validate-form">

					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
<!-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
                        <!-- <input class="input100" type="email" name="email" id="email" placeholder="Email" value=" required> -->
                        <input class="input100" type="email" name="email" id="email" placeholder="Enter email" value="<?php if(isset($username))echo $username; ?>" required>
<!-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
                        <span class="focus-input100"></span>
						            <span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<!-- <input class="input100" type="password" name="password" id="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required> -->
            <input class="input100" type="password" name="password" class="form-control" id="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required>

            <span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn">
							Login
						</button>
					</div>

<!-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
   
    <br>
    <center>
    <div class="form-check">
      <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>>
 
      <label class="form-check-label" for="rememberMe">Remember me</label>
    </div>
</center>
<!-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
<br>
					<div class="text-right">
           <a class="txt2" href="authen/signUp">
							<p>Create your Account</p>
              <i class="fa fa-long-arrow-right m-l-12" aria-hidden="true"></i>
              <div class="text-lef">
						  <a class="txt2" href="<?php echo $this->url->getBaseUri(); ?>">
							<p>Back to page</p>
							<i class="fa fa-long-arrow-left m-l-5" aria-hidden="true"></i>
						</a>
          </div>
            </a>
          </div>
				</form>
			</div>
		</div>
	</div>

<!--===============================================================================================-->
	<script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script><script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/tilt/tilt.jquery.min.js"></script>
	<script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

<!--===============================================================================================-->
	<script src="js/main.js"></script>



</body></html>

